name: aiwall
description: AIWall - Smart Assistant
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  youtube_player_flutter: ^9.1.1
  share_plus: ^7.2.2
  video_player: ^2.9.1
  google_fonts: ^6.2.1
  speech_to_text: ^6.6.0
  flutter_tts: ^4.0.2
  connectivity_plus: ^6.0.5
  avatar_glow: ^2.0.2
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.3.0
  carousel_slider: ^5.0.0
  provider: ^6.1.2
  path: ^1.9.0
  webview_flutter: ^4.2.2
  flutter_inappwebview: ^6.1.1+1
  visibility_detector: ^0.4.0+2
  youtube_explode_dart: ^2.2.1
  video_thumbnail: ^0.5.3
  image: ^4.2.0
  shared_preferences: ^2.3.0
  geolocator: ^12.0.0
  lucide_icons: ^0.257.0
  google_maps_flutter: ^2.9.0
  firebase_core: ^3.3.0
  cloud_firestore: ^5.2.1
  uuid: ^4.4.2
  firebase_crashlytics: ^4.1.0
  webview_flutter_android: ^3.10.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/videos/sample.mp4
    - assets/images/profile.jpg
    - assets/images/news1.jpg
    - assets/images/news2.jpg
    - assets/images/news3.jpg
    - assets/images/article1.jpg
    - assets/images/video1.jpg
    - assets/images/trending1.png
    - assets/images/logo.png
    - assets/images/creator.jpg
    - assets/images/mock_map.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"

flutter_native_splash:
  color: "#000000"
  image: assets/images/logo.png
  android: true
  ios: false
  android_gravity: center